language: python
python:
- 3.5
install:
- pip install -r requirements.txt
script: ./test.sh
env:
  global:
  - secure: Qx+34577hoxuxCnkk93WvVnHzZrQG9YZwBX1ori0cf433VNzfTVL6sFdMHfOCjCyLgkY91b19qgbgcfJ5VPgFi5pZeIXBjPzP3qVh5NaK6mzs7avh9gUdHF1GUTpDK6JtvDqpz2lZuZtsVVqxwX2HGn1VE99KHHZXIFf10annxGnm/oBm6tvYfSEXgzqUTZt8R55whKjWcxVzGrumDo3G80bwtWG5HaAMRptUaZSJi0CzCkmnkMkb+oFhYTtypVMhlxBCgi/5vRCHkLeJl4lmV8IYCtufToTB4ScHxiZs5rQXAy7BNmwLC8j2L/aaA10fsQpHhSsAW5BO9sKZdM8qiH3aTvtMRqGiIVU86hvsMnepNCO7NWaUG3SE5vXUt5jQwk3fNiKa5Y5De1H+tF1583ZX4oetxATcB1o+CUrUp3qcEgfsZ988I3q/ncYJkBCB8yLfIDsebBEY5r8gQ48NL1InxVU8/hVG1HGirds4grvnq6yv8kdwAOluxvr79ygjogWhj7caC4fxAlbLnWW28QtwsA+QCAoK1jRjczL0F5HRpZkvLg4HoQ3ypdrYWx50sxB8sjrduoB+0vSPN8pNMi1wf6Z8rEFhXjc1sI7SfOIFXxGBk8Qh+NYEyuHX+tsyLV57MWSoCRXxy5SxciUD6A4hp4akHn86w5lJvnRu5s=
